language: rust
sudo: false

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - gcc-multilib

os:
    - linux
    - osx

rust:
    - 1.9.0
    - 1.14.0
    - nightly

env:
    matrix:
        - ARCH=x86_64
        - ARCH=i686

install:
    - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then OS=unknown-linux-gnu; else OS=apple-darwin; fi
    - export HOST=$ARCH-$OS
    - curl -SfLO "https://static.rust-lang.org/rustup/dist/$HOST/rustup-init"
    - chmod u+x rustup-init
    - ./rustup-init -y --default-host "$HOST" --default-toolchain "$TRAVIS_RUST_VERSION"
    - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
    - rustc -vV
    - cargo -vV

script:
    - cargo build --no-default-features
    - cargo test --no-default-features
    - cargo build
    - cargo test
    - if [ "$TRAVIS_RUST_VERSION" = 'nightly' ]; then cargo bench; fi
    - cargo test --manifest-path extprim_tests/Cargo.toml

after_success:
    - cargo install cargo-kcov
    - cargo kcov --print-install-kcov-sh | bash
    - cargo kcov --coveralls -- --verify
