language: rust
sudo: false

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - gcc-multilib

matrix:
    fast_finish: true
    include:
        - os: linux
          rust: 1.22.1
          env: ARCH=x86_64
        - os: linux
          rust: stable
          env: ARCH=x86_64
        - os: linux
          rust: beta
          env: ARCH=x86_64
        - os: linux
          rust: nightly
          env: ARCH=x86_64
        - os: osx
          rust: stable
          env: ARCH=x86_64
        - os: linux
          rust: nightly
          env: ARCH=i686

install:
    - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then OS=unknown-linux-gnu; else OS=apple-darwin; fi
    - export HOST=$ARCH-$OS
    - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
    - export FLAGS=""
    - if [ "$ARCH" != x86_64 ]; then rustup target add "$HOST"; export FLAGS="--target $HOST"; fi
    - rustc -vV
    - cargo -vV

script:
    - cargo update
    - cargo build $FLAGS --all --no-default-features
    - cargo test $FLAGS --all --no-default-features
    - cargo clean
    - cargo build $FLAGS --all --all-features
    - cargo test $FLAGS --all --all-features
    - if [ "$TRAVIS_RUST_VERSION" = 'nightly' ]; then cargo bench --all; fi

after_success:
    - >
      if [ "$TRAVIS_OS_NAME" = 'linux' ]; then
        cargo install cargo-kcov &&
        ( cargo kcov --print-install-kcov-sh | bash ) &&
        cargo kcov --coveralls -- --verify;
      fi
