# based on https://github.com/alexcrichton/gcc-rs/blob/master/.travis.yml
# and https://github.com/rust-lang/libc/blob/master/.travis.yml

language: rust
sudo: false

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - gcc-multilib

os:
    - linux
    - osx

rust:
    - 1.8.0
    - nightly

env:
    global:
        - TRAVIS_CARGO_NIGHTLY_FEATURE=""  # <-- we use build.rs to distinguish nightly and stable.
    matrix:
        - ARCH=x86_64
        - ARCH=i686

matrix:
    allow_failures:
        - env: ARCH=i686
        # FIXME: all i686 build panics with the message "Box<Any>", cause all `should_panic` tests to fail.

install:
    - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then OS=unknown-linux-gnu; else OS=apple-darwin; fi
    - SYSROOT=$(rustc --print sysroot)
    - export HOST=$ARCH-$OS
    - |
        if [ ! -d "$SYSROOT/lib/rustlib/$HOST" ]; then
            curl -SfLO "https://static.rust-lang.org/dist/rust-$TRAVIS_RUST_VERSION-$HOST.tar.gz" &&
            tar xf "rust-$TRAVIS_RUST_VERSION-$HOST.tar.gz" "rust-$TRAVIS_RUST_VERSION-$HOST/rust-std-$HOST/lib/rustlib/$HOST" &&
            mv "rust-$TRAVIS_RUST_VERSION-$HOST/rust-std-$HOST/lib/rustlib/$HOST" "$SYSROOT/lib/rustlib"
        fi

before_script:
    - pip install 'travis-cargo<0.2' --user

script:
    - cargo test --target "$HOST"
    - cargo bench --target "$HOST"
    - cargo test --target "$HOST" --manifest-path extprim_tests/Cargo.toml

after_success:
    - if [ "$HOST" = 'x86_64-unknown-linux-gnu' -a "$TRAVIS_RUST_VERSION" = 'stable' ]; then cargo doc && travis-cargo doc-upload; fi
    - travis-cargo coveralls --no-sudo --verify

