os: Visual Studio 2015

platform:
    - Win32
    - x64

environment:
    matrix:
        - RUST: 1.8.0
          ABI: msvc
        - RUST: 1.8.0
          ABI: gnu
        - RUST: 1.9.0
          ABI: msvc
        - RUST: 1.9.0
          ABI: gnu
        - RUST: nightly
          ABI: msvc
        - RUST: nightly
          ABI: gnu

cache:
    - rust -> appveyor.*
    - target -> Cargo.toml
    - extprim_tests\target -> **\Cargo.toml
    - '%USERPROFILE%\.cargo'

build_script: appveyor.bat

