[package]
name = "extprim"
version = "1.0.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Extra primitive types (u128, i128)"
repository = "https://github.com/kennytm/extprim"
license = "MIT OR Apache-2.0"
keywords = ["primitives","u128","i128"]
#documentation = ""
build = "build.rs"

include = [
    "build.rs",
    "src/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE*.txt",
]

[dependencies]
lazy_static = "0.2.0"
rand = "0.3.14"
num-traits = "0.1.32"

[build-dependencies]
rustc_version = "0.1.7"

