[package]
name = "extprim"
version = "0.5.1"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Extra primitive types (u128, i128)"
repository = "https://github.com/kennytm/extprim"
license = "Apache-2.0"
keywords = ["primitives","u128","i128"]
documentation = "http://www.rust-ci.org/kennytm/extprim/doc/extprim/index.html"

include = [
    "src/*.rs",
    "tests/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE.txt",
]

[lib]
name = "extprim"
crate-type = ["dylib", "rlib"]

[dependencies]
lazy_static = "*"
rand = "*"
