[package]
name = "extprim"
version = "0.2.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Extra primitive types (u128, i128)"
repository = "https://github.com/kennytm/extprim"
license = "Apache-2.0"
keywords = ["primitives","u128","i128"]



