[package]
name = "extprim"
version = "1.2.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Extra primitive types (u128, i128)"
repository = "https://github.com/kennytm/extprim"
license = "MIT OR Apache-2.0"
keywords = ["primitives","u128","i128"]
documentation = "https://kennytm.github.io/extprim/extprim/index.html"
build = "build.rs"

include = [
    "build.rs",
    "src/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE*.txt",
]

[workspace]
members = ["extprim_literals", "extprim_tests"]

[dependencies]
rand = { version = "0.3.14", optional = true }
num-traits = "0.1.33"

[build-dependencies]
rustc_version = "0.1.7"

[features]
default = ["use-std"]
use-std = ["rand"]

