[package]
name = "extprim_literals"
version = "0.2.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Literal macros for extprim"
repository = "https://github.com/kennytm/extprim"
license = "Apache-2.0"

[lib]
name = "extprim_literals"
plugin = true

[dependencies.extprim]
path = ".."
version = "0.2.0"

