[package]
name = "extprim_tests"
version = "1.1.2"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Test case for extprim literals"
repository = "https://github.com/kennytm/extprim"
license = "MIT OR Apache-2.0"
build = "build.rs"

include = [
    "build.rs",
    "tests/*.rs*",
    "Cargo.toml",
]

[dev-dependencies]
extprim = { path = "../", version = "1.1.2" }
extprim_literals = { path = "../extprim_literals", version = "1.1.2" }

[build-dependencies]
syntex = "0.38.0"
extprim_literals = { path = "../extprim_literals", version = "1.1.2" }
rustc_version = "0.1.7"

